Repository openstack-k8s-operators/swift-operator, pull requests merged in 2023-07, with the labels that each got.

#15 Remove openstack from workflow name
  .github/workflows/build-swift-operator.yaml
Labels: approved, lgtm

#16 Watch RBAC resources to trigger reconcile
  controllers/swift_controller.go
Labels: approved, lgtm

#17 CSV: Set operator-type: non-standalone
  config/manifests/bases/swift-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#20 Add and configure renovate to pin k8s and controller-runtime for dev preview
  api/go.mod
  go.mod
  go.sum
  renovate.json
Labels: approved, lgtm

#22 Ctrl manager labels for webhooks and logging
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/service.yaml
Labels: approved, lgtm

#21 Bump lib-common modules and services to v0.1.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/functional/suite_test.go
Labels: approved, lgtm

#23 Use central renovate config
  renovate.json
Labels: lgtm

#29 Add missing tidy target to Makefile
  Makefile
Labels: approved

#31 Remove config/manager/kustomization.yaml from .gitignore
  .gitignore
Labels: approved, lgtm

#32 Revert "Remove config/manager/kustomization.yaml from .gitignore"
  .gitignore
Labels: approved, lgtm

#33 Remove endpoint url from status
  api/v1beta1/swiftproxy_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/swift.openstack.org_swiftproxies.yaml
  controllers/swiftproxy_controller.go
Labels: approved, lgtm

#34 Avoid bumping own api module by renovate
  renovate.json
Labels: approved, lgtm
