Repository openstack-k8s-operators/swift-operator, pull requests merged in 2024-02, with the labels that each got.

#102 Use memcached instance
  README.md
  api/bases/swift.openstack.org_swiftproxies.yaml
  api/bases/swift.openstack.org_swifts.yaml
  api/bases/swift.openstack.org_swiftstorages.yaml
  api/v1beta1/swift_types.go
  api/v1beta1/swift_webhook.go
  api/v1beta1/swiftproxy_types.go
  api/v1beta1/swiftstorage_types.go
  config/crd/bases/swift.openstack.org_swiftproxies.yaml
  config/crd/bases/swift.openstack.org_swifts.yaml
  config/crd/bases/swift.openstack.org_swiftstorages.yaml
  config/default/manager_default_images.yaml
  config/rbac/role.yaml
  controllers/swift_controller.go
  controllers/swiftproxy_controller.go
  controllers/swiftstorage_controller.go
  go.mod
  go.sum
  main.go
  pkg/swift/const.go
  pkg/swiftproxy/deployment.go
  pkg/swiftproxy/templates.go
  pkg/swiftstorage/statefulset.go
  pkg/swiftstorage/templates.go
  templates/swiftproxy/config/proxy-server.conf
  templates/swiftstorage/config/object-expirer.conf
  tests/kuttl/tests/basic-deploy/01-assert-deploy-swift.yaml
Labels: approved, lgtm

#105 Run swift-recon-cron
  pkg/swiftstorage/statefulset.go
  pkg/swiftstorage/volumes.go
Labels: approved

#107 Add networkv1 to scheme
  go.mod
  main.go
Labels: approved

#108 Add missing networkattachment annotations
  controllers/swiftproxy_controller.go
  controllers/swiftstorage_controller.go
  pkg/swiftproxy/deployment.go
  pkg/swiftstorage/statefulset.go
Labels: approved

#104 Run container-sharder
  api/bases/swift.openstack.org_swifts.yaml
  api/bases/swift.openstack.org_swiftstorages.yaml
  api/v1beta1/swiftstorage_types.go
  config/crd/bases/swift.openstack.org_swifts.yaml
  config/crd/bases/swift.openstack.org_swiftstorages.yaml
  controllers/swift_controller.go
  pkg/swiftstorage/statefulset.go
  templates/swiftstorage/config/container-server.conf
  templates/swiftstorage/config/internal-client.conf
Labels: approved

#114 Make swift-operator image FIPS-compliant
  Dockerfile
Labels: approved, lgtm

#119 Set FIPS feature annotation in the CSV
  .prow_ci.env
  Makefile
  config/manifests/bases/swift-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#118 Update Networkpolicy to allow traffic from dataplane and SwiftRing
  controllers/swiftstorage_controller.go
  pkg/swiftring/funcs.go
  pkg/swiftstorage/networkpolicy.go
Labels: approved, lgtm, EDPM

#116 Add ring config options
  api/bases/swift.openstack.org_swiftrings.yaml
  api/bases/swift.openstack.org_swifts.yaml
  api/v1beta1/swiftring_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/swift.openstack.org_swiftrings.yaml
  config/crd/bases/swift.openstack.org_swifts.yaml
  pkg/swiftring/job.go
  templates/swiftring/bin/swift-ring-rebalance.sh
Labels: approved, lgtm

#123 Recreate go.sum files to fix merge jobs
  Makefile
  api/go.sum
  config/manager/kustomization.yaml
  config/manifests/bases/swift-operator.clusterserviceversion.yaml
Labels: do-not-merge/hold

#124 Unique LeaderElectionID
  main.go
Labels: approved, lgtm

#127 Bump golangci-lint
  .golangci.yaml
  .pre-commit-config.yaml
Labels: approved, lgtm

#128 [renovate]Remove golang constraint
  renovate.json
Labels: approved, lgtm

#137 Set default reader roles for Swift
  templates/swiftproxy/config/proxy-server.conf
Labels: approved

#138 Add default dispersion.conf
  templates/swiftproxy/config/dispersion.conf
Labels: approved

#106 Add DefaultConfigOverwrite option
  api/bases/swift.openstack.org_swiftproxies.yaml
  api/bases/swift.openstack.org_swifts.yaml
  api/bases/swift.openstack.org_swiftstorages.yaml
  api/v1beta1/swiftproxy_types.go
  api/v1beta1/swiftstorage_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/swift.openstack.org_swiftproxies.yaml
  config/crd/bases/swift.openstack.org_swifts.yaml
  config/crd/bases/swift.openstack.org_swiftstorages.yaml
  controllers/swift_controller.go
  pkg/swiftproxy/deployment.go
  pkg/swiftproxy/templates.go
  pkg/swiftstorage/statefulset.go
  pkg/swiftstorage/templates.go
  templates/common/ring-sync.sh
  templates/swiftproxy/config/00-proxy-server.conf
  templates/swiftstorage/config/00-account-server.conf
  templates/swiftstorage/config/00-container-server.conf
  templates/swiftstorage/config/00-object-expirer.conf
  templates/swiftstorage/config/00-object-server.conf
  tests/kuttl/tests/basic-deploy_tls/01-assert-deploy-swift.yaml
Labels: approved

#140 Create Keystone roles for Swift RBAC
  controllers/swiftproxy_controller.go
Labels: approved

#120 Add DNSData entries for SwiftStorage service pods
  config/rbac/role.yaml
  controllers/swiftstorage_controller.go
  main.go
  pkg/swiftstorage/dnsdata.go
  pkg/swiftstorage/funcs.go
Labels: approved, lgtm, EDPM

#142 Enable S3 and staticweb proxy middlewares
  templates/swiftproxy/config/00-proxy-server.conf
Labels: approved

#144 Set pod affinity to spread services across OCP workers
  pkg/swift/funcs.go
  pkg/swiftproxy/deployment.go
  pkg/swiftstorage/statefulset.go
Labels: approved, lgtm

#143 Add finalizer for SwiftRing and ConfigMap
  controllers/swiftring_controller.go
  templates/swiftring/bin/swift-ring-rebalance.sh
Labels: approved, lgtm

#135 Add Dataplane devices to rings
  api/go.mod
  api/go.sum
  api/v1beta1/swiftring_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/rbac/role.yaml
  controllers/swiftring_controller.go
  controllers/swiftstorage_controller.go
  go.mod
  go.sum
  main.go
  pkg/swiftring/const.go
  pkg/swiftring/funcs.go
  pkg/swiftring/templates.go
  pkg/swiftstorage/funcs.go
  pkg/swiftstorage/templates.go
  tests/kuttl/deps/dataplane.openstack.org_openstackdataplanenodesets.yaml
  tests/kuttl/tests/basic-deploy/00-deps.yaml
  tests/kuttl/tests/basic-deploy_tls/00-deps.yaml
Labels: approved, EDPM

#148 Add Barbican support
  api/bases/swift.openstack.org_swiftproxies.yaml
  api/bases/swift.openstack.org_swifts.yaml
  api/v1beta1/swiftproxy_types.go
  config/crd/bases/swift.openstack.org_swiftproxies.yaml
  config/crd/bases/swift.openstack.org_swifts.yaml
  config/rbac/role.yaml
  controllers/swift_controller.go
  controllers/swiftproxy_controller.go
  go.mod
  go.sum
  main.go
  pkg/swiftproxy/barbican.go
  pkg/swiftproxy/const.go
  pkg/swiftproxy/templates.go
  templates/common/ring-sync.sh
  templates/swiftproxy/config/00-proxy-server.conf
  templates/swiftproxy/config/keymaster.conf
Labels: approved, lgtm

#149 Refactor ring rebalance
  controllers/swiftring_controller.go
  pkg/swiftring/funcs.go
  pkg/swiftring/job.go
  pkg/swiftring/templates.go
  pkg/swiftring/volumes.go
  templates/swiftring/bin/swift-ring-rebalance.sh
  templates/swiftring/bin/swift-ring-tool
Labels: approved, lgtm
